version: "3.9"

services:
  spark-master:
    build: ./spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8080"
      - "7077:7077"
    restart: always
    volumes:
      - ./spark/shard-spark-data:/tmp
      - ./data-mock:/data # Mock data path because some read SparkFiles function may cause an error
    networks:
      - airflow-network  # Connect to Airflow's network (docker network ls) to see networks from astro name because it's separate network from airflow

  spark-worker:
    build: ./spark
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no    
    restart: always
    volumes:
      - ./spark/shard-spark-data:/tmp
      - ./data-mock:/data # Mock data path because some read Spark read function may cause an error
    networks:
      - airflow-network # default astro-airflow is in other network to list all network use command'docker network ls'

  spark-worker2:
    build: ./spark
    environment:
      - SPARK_WORKLOAD=worker
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no    
    restart: always
    volumes:
      - ./spark/shard-spark-data:/tmp
      - ./data-mock:/data # Mock data path because some read Spark read function may cause an error
    networks:
      - airflow-network 

  minio:
    env_file: .env
    image: minio/minio:latest 
    container_name: minio-bucket
    ports:
      - "9000:9000" # webUI port
      - "9001:9001" # API port
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - ./bucket-data:/data
    command: server --address ":9001" --console-address ":9000" /data
    restart: always
    networks:
      - airflow-network

networks:
  airflow-network:
    external: true  # Reference Airflow's existing network
    name: airflow-delta-etl_fcb87b_airflow # ID or name of external network

